### ISSUE TITLE
Add an action for SCMP_ACT_KILL_PROCESS

### ISSUE THREAD

**Issue by danderson** [kpcyrd/syscallz-rs#13]
The current `Action::Kill` implements `SCMP_ACT_KILL`, which only kills the calling _thread_, not the entire calling process. This is almost always the wrong thing to do, because most programs fall apart if you randomly kill just one thread and not everything else.

Later on, seccomp added `SCMP_ACT_KILL_PROCESS` to implement the intuitive meaning of "kill the caller", but it's not mapped into syscallz.

Should be a trivial PR which I'll write momentarily. Opening this issue to ask two things:

1. Should we follow the C API's lead and have `Action::Kill` and `Action::KillProcess`, or should we invert it so that `Action::Kill` does the intuitive thing and `Action::KillThread` does the thing almost nobody wants? This obviously breaks compatibility, I don't know what your policy is on that.
2. `SCMP_ACT_KILL_PROCESS` was added in Linux v4.14. How old a kernel do we want to support? I'm still a Rust novice, so I don't know if there's conditional compilation we can leverage here to support it only if the underlying library has it.

**Comment by danderson** [comment]
One more roadbump: the constant needs to be defined in `seccomp-sys` first so we can use it in syscallz. Working on that first.

**Comment by kpcyrd** [comment]
1. That seems like a good idea. I would include it in a semver-breaking update, also pinging @Nugine and @myfreeweb so they are aware and have a chance to voice concerns if there are any.
2. Since both the latest debian stable and the latest ubuntu lts have a recent enough kernel I think it's fair to require a kernel that is >= 4.14. There is theoretically a way to test for this using a custom `build.rs` but I don't think it's worth it.

Getting it included in a new `seccomp-sys` release is probably the bigger challenge. Feel free to link to the issue so me and others can subscribe. :)

**Comment by danderson** [comment]
Sent polachok/seccomp-sys#9 to add the required constant, and #14 here to propagate the change (doesn't build yet). I made the breaking change suggested above, but it's easy to switch back if we prefer to mirror libseccomp's API.

**Comment by kpcyrd** [comment]
This has been implemented in the latest version. It's also set as the default action now. Thanks a lot!
